-- MySQL Script generated by MySQL Workbench
-- ter 23 jun 2020 08:18:07 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema covidFapesp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema covidFapesp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `covidFapesp` DEFAULT CHARACTER SET utf8 ;
USE `covidFapesp` ;

-- -----------------------------------------------------
-- Table `covidFapesp`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`sexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `covidFapesp`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`institution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `institution` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covidFapesp`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covidFapesp`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covidFapesp`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`uf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uf` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covidFapesp`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`patient` (
  `id` VARCHAR(45) NOT NULL,
  `IC_SEXO` INT NULL,
  `AA_NASCIMENTO` VARCHAR(45) NULL,
  `CD_PAIS` INT NULL,
  `CD_INSTITUICAO` INT NULL,
  `CD_UF` INT NULL,
  `CD_CEPREDUZIDO` VARCHAR(45) NULL,
  `CD_MUNICIPIO` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`IC_SEXO` ASC),
  INDEX `id_idx1` (`CD_INSTITUICAO` ASC),
  INDEX `id_idx2` (`CD_MUNICIPIO` ASC),
  INDEX `id_idx3` (`CD_PAIS` ASC),
  INDEX `id_idx4` (`CD_UF` ASC),
  CONSTRAINT `ic_sexo`
    FOREIGN KEY (`IC_SEXO`)
    REFERENCES `covidFapesp`.`sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_instituicao`
    FOREIGN KEY (`CD_INSTITUICAO`)
    REFERENCES `covidFapesp`.`institution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_municipio`
    FOREIGN KEY (`CD_MUNICIPIO`)
    REFERENCES `covidFapesp`.`municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pais`
    FOREIGN KEY (`CD_PAIS`)
    REFERENCES `covidFapesp`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_uf`
    FOREIGN KEY (`CD_UF`)
    REFERENCES `covidFapesp`.`uf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covidFapesp`.`exame_laboratorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`exame_laboratorial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` VARCHAR(45) NULL,
  `ID_ATENDIMENTO` VARCHAR(45) NULL,
  `DT_COLETA` VARCHAR(45) NULL,
  `DE_ORIGEM` VARCHAR(450) NULL,
  `DE_EXAME` TEXT NULL,
  `DE_ANALITO` VARCHAR(450) NULL,
  `DE_RESULTADO` TEXT NULL,
  `CD_UNIDADE` VARCHAR(45) NULL,
  `DE_VALOR_REFERENCIA` VARCHAR(450) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`ID_PACIENTE` ASC),
  CONSTRAINT `id_paciente_exame`
    FOREIGN KEY (`ID_PACIENTE`)
    REFERENCES `covidFapesp`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covidFapesp`.`desfecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`desfecho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` VARCHAR(45) NULL,
  `ID_ATENDIMENTO` VARCHAR(450) NULL,
  `DT_ATENDIMENTO` VARCHAR(45) NULL,
  `DE_TIPO_ATENDIMENTO` VARCHAR(450) NULL,
  `ID_CLINICA` VARCHAR(450) NULL,
  `DE_CLINICA` VARCHAR(450) NULL,
  `DT_DESFECHO` VARCHAR(45) NULL,
  `DE_DESFECHO` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`ID_PACIENTE` ASC),
  CONSTRAINT `id_paciente_desfecho`
    FOREIGN KEY (`ID_PACIENTE`)
    REFERENCES `covidFapesp`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covidFapesp`.`parse_exame_laboratorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covidFapesp`.`parse_exame_laboratorial` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_EXAME` INT NULL,
  `ID_PACIENTE` VARCHAR(45) NULL,
  `LOWER_BOUND` VARCHAR(45) NULL,
  `UPPER_BOUND` VARCHAR(45) NULL,
  `IS_ABNORMAL` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_parse_exame_laboratorial_1_idx` (`ID_PACIENTE` ASC),
  INDEX `fk_parse_exame_laboratorial_2_idx` (`ID_EXAME` ASC),
  CONSTRAINT `fk_parse_exame_laboratorial_1`
    FOREIGN KEY (`ID_PACIENTE`)
    REFERENCES `covidFapesp`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parse_exame_laboratorial_2`
    FOREIGN KEY (`ID_EXAME`)
    REFERENCES `covidFapesp`.`exame_laboratorial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
